
/**
 * Utility to fix common JSON syntax errors before parsing.
 * Useful for handling JSON generated by LLMs or pasted by users that might have:
 * - Unescaped backslashes (common in LaTeX math)
 * - Trailing commas
 * - Improperly escaped newlines/control characters inside strings
 */

export const repairJson = (jsonString) => {
  if (!jsonString) return '';

  let result = '';
  let i = 0;
  let inString = false;
  let lastCommaIndex = -1;
  const fixStats = { backslashes: 0, quotes: 0, controlChars: 0, trailingCommas: 0 };

  const input = jsonString.trim();

  while (i < input.length) {
    const char = input[i];

    if (!inString) {
      if (char === '"') {
        inString = true;
        result += char;
        i++;
        continue;
      }

      if (char === ',') {
        lastCommaIndex = result.length;
        result += char;
        i++;
        continue;
      }

      if ((char === ']' || char === '}') && lastCommaIndex !== -1) {
        const textSinceComma = result.substring(lastCommaIndex + 1);
        if (/^\s*$/.test(textSinceComma)) {
          result = result.substring(0, lastCommaIndex) + textSinceComma;
          fixStats.trailingCommas++;
        }
        lastCommaIndex = -1;
      }

      result += char;
      i++;
      continue;
    }

    // Inside String
    if (char === '"') {
      // Look ahead for next significant character
      let nextSig = '';
      for (let j = i + 1; j < input.length; j++) {
        if (!/\s/.test(input[j])) {
          nextSig = input[j];
          break;
        }
      }
      
      // Heuristic: Is this a closing quote?
      // It's a closing quote if it's followed by structural JSON characters.
      // We also check for '"' which handles the common AI error of missing commas.
      const isClosingHeuristic = 
        nextSig === ':' || 
        nextSig === '}' || 
        nextSig === ']' || 
        nextSig === ',' || 
        nextSig === '"' || 
        nextSig === '';

      if (isClosingHeuristic) {
        inString = false;
        result += char;
        i++;
      } else {
        // Looks like an unescaped internal quote! (e.g. "He said "Hello"")
        const snippet = input.substring(Math.max(0, i - 20), Math.min(input.length, i + 20));
        console.log(`  - Escaping quote in snippet: "...${snippet}..."`);
        result += '\\"';
        fixStats.quotes++;
        i++;
      }
      continue;
    }

    if (char === '\\') {
      const nextChar = input[i + 1];
      if (nextChar && /["\\/bfnrtu]/.test(nextChar)) {
        if (nextChar === 'u') {
          const hexPart = input.substring(i + 2, i + 6);
          if (/^[0-9a-fA-F]{4}$/.test(hexPart)) {
            result += '\\u' + hexPart;
            i += 6;
            continue;
          } else {
            console.log(`  - Escaping invalid unicode backslash at pos ${i}`);
            result += '\\\\';
            fixStats.backslashes++;
            i++;
            continue;
          }
        } else {
          result += '\\' + nextChar;
          i += 2;
          continue;
        }
      } else {
        // Raw backslash (like \frac)
        console.log(`  - Escaping raw backslash (e.g. LaTeX) at pos ${i}`);
        result += '\\\\';
        fixStats.backslashes++;
        i++;
        continue;
      }
    }

    if (char === '\n') {
      result += '\\n';
      fixStats.controlChars++;
      i++;
      continue;
    }
    if (char === '\r') {
      if (input[i + 1] === '\n') {
        result += '\\n';
        i += 2;
      } else {
        result += '\\r';
        i++;
      }
      fixStats.controlChars++;
      continue;
    }
    if (char === '\t') {
      result += '\\t';
      fixStats.controlChars++;
      i++;
      continue;
    }

    const code = char.charCodeAt(0);
    if (code < 32) {
        if (code === 8) result += '\\b';
        else if (code === 12) result += '\\f';
        fixStats.controlChars++;
        i++; 
        continue; 
    }

    result += char;
    i++;
  }

  if (fixStats.backslashes > 0 || fixStats.quotes > 0 || fixStats.controlChars > 0 || fixStats.trailingCommas > 0) {
    console.group('🛠️ JSON Auto-Repair Summary');
    console.log('Fixed Backslashes:', fixStats.backslashes);
    console.log('Fixed Unescaped Quotes:', fixStats.quotes);
    console.log('Fixed Control Chars (newlines/tabs):', fixStats.controlChars);
    console.log('Removed Trailing Commas:', fixStats.trailingCommas);
    console.groupEnd();
  }

  return result;
};

/**
 * Attempts to parse JSON, applying repairs if initial parse fails.
 * Returns { data: parsedObject } on success.
 * Returns { error: message, line, column, snippet } on failure.
 */
export const safeJsonParse = (jsonString) => {
  try {
    return { data: JSON.parse(jsonString) };
  } catch (initialError) {
    console.warn('Initial JSON parse failed, attempting repair...');
    let repaired = '';
    try {
      repaired = repairJson(jsonString);
      return { data: JSON.parse(repaired) };
    } catch (repairError) {
      console.error('JSON repair also failed:', repairError.message);
      
      const targetError = repairError;
      const targetString = repaired || jsonString;

      const posMatch = targetError.message.match(/at position (\d+)/);
      if (posMatch) {
        const pos = parseInt(posMatch[1], 10);
        console.log('Error around repaired position:', targetString.substring(Math.max(0, pos - 50), Math.min(targetString.length, pos + 50)));
        const lines = targetString.substring(0, pos).split(/\r?\n/);
        const line = lines.length;
        const column = lines[lines.length - 1].length + 1;
        
        // Extract a snippet around the error
        const start = Math.max(0, pos - 40);
        const end = Math.min(targetString.length, pos + 40);
        const snippet = targetString.substring(start, end);
        const pointer = ' '.repeat(Math.min(pos, 40)) + '^';

        return {
          error: targetError.message,
          line,
          column,
          snippet,
          pointer,
          isRepaired: !!repaired
        };
      }

      return { error: targetError.message };
    }
  }
};
